apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ywf40f6l1-go
  janus-idp.io/tekton: ywf40f6l1-go
  backstage.io/kubernetes-id: ywf40f6l1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ywf40f6l1-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
