apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ywf40f6l1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ywf40f6l1-go 
  name: ywf40f6l1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ywf40f6l1-go 
